<a href="https://colab.research.google.com/github/ArifaAsha/LearningML/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [96]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [97]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1]  # -1 = last column
y = dataset.iloc[:, -1:] #

In [ ]:
x

In [ ]:
y

## Taking care of missing data

In [26]:
from sklearn.impute import SimpleImputer
X = np.array(X)
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In [29]:
!pip install pandas


In [59]:
# Importing the necessary libraries
import numpy as np
from sklearn.impute import SimpleImputer
import pandas as pd
# Load the dataset
dataset = pd.read_csv('pima-indians-diabetes.csv')

# Identify missing data (assumes that missing data is represented as NaN)
missing_data = dataset.isna()
X = dataset.iloc[:, :-1]  # -1 = last column
y = dataset.iloc[:, -1:] #
# print(X)

# Print the number of missing entries in each column
print(missing_data.sum())

# imputer = SimpleImputer(strategy='median')
# dataset.iloc[:, 0] = imputer.fit_transform(dataset.iloc[:, 0].values.reshape(-1, 1))

# Configure an instance of the SimpleImputer class
imputer = SimpleImputer(missing_values=np.NAN, strategy='mean')


#Fit the imputer on the DataFrame
imputer.fit(X[1:7])

# Apply the transform to the DataFrame
X[1:7] = imputer.transform(X[1:7])

#Print your updated matrix of features
print(X)

6        0
148      0
72       0
35       0
0        0
33.6     0
0.627    0
50       0
1        0
dtype: int64
        6    148    72    35      0  33.6  0.627    50
0     1.0   85.0  66.0  29.0    0.0  26.6  0.351  31.0
1     8.0  183.0  64.0   0.0    0.0  23.3  0.672  32.0
2     1.0   89.0  66.0  23.0   94.0  28.1  0.167  21.0
3     0.0  137.0  40.0  35.0  168.0  43.1  2.288  33.0
4     5.0  116.0  74.0   0.0    0.0  25.6  0.201  30.0
..    ...    ...   ...   ...    ...   ...    ...   ...
762  10.0  101.0  76.0  48.0  180.0  32.9  0.171  63.0
763   2.0  122.0  70.0  27.0    0.0  36.8  0.340  27.0
764   5.0  121.0  72.0  23.0  112.0  26.2  0.245  30.0
765   1.0  126.0  60.0   0.0    0.0  30.1  0.349  47.0
766   1.0   93.0  70.0  31.0    0.0  30.4  0.315  23.0

[767 rows x 8 columns]


### Encoding the Independent Variable

In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1]  # -1 = last column

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)


[[1.0e+00 0.0e+00 0.0e+00 4.4e+01 7.2e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.7e+01 4.8e+04]
 [0.0e+00 1.0e+00 0.0e+00 3.0e+01 5.4e+04]
 [0.0e+00 0.0e+00 1.0e+00 3.8e+01 6.1e+04]
 [0.0e+00 1.0e+00 0.0e+00 4.0e+01     nan]
 [1.0e+00 0.0e+00 0.0e+00 3.5e+01 5.8e+04]
 [0.0e+00 0.0e+00 1.0e+00     nan 5.2e+04]
 [1.0e+00 0.0e+00 0.0e+00 4.8e+01 7.9e+04]
 [0.0e+00 1.0e+00 0.0e+00 5.0e+01 8.3e+04]
 [1.0e+00 0.0e+00 0.0e+00 3.7e+01 6.7e+04]]


In [99]:
from sklearn.preprocessing import LabelEncoder

dataset = pd.read_csv('Data.csv')
y = dataset.iloc[:, -1:] #

le = LabelEncoder()
y =le.fit_transform(y)
print(y)


[0 1 0 0 1 1 0 1 0 1]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# Importing the necessary libraries
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Load the dataset
dataset = pd.read_csv('titanic.csv')

X = dataset[:]
y = dataset['Survived']

categorical_features = ['Sex', 'Embarked', 'Pclass']

# Implement an instance of the ColumnTransformer class
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), categorical_features)], remainder='passthrough')

# Apply the fit_transform method on the instance of ColumnTransformer
X = np.array(ct.fit_transform(X))

# Use LabelEncoder to encode binary categorical data
le = LabelEncoder()
y = le.fit_transform(dataset['Survived'])

# Print the updated matrix of features and the dependent variable vector
print(X)
print(y)


### Encoding the Dependent Variable

## Splitting the dataset into the Training set and Test set

In [102]:
from sklearn.model_selection import train_test_split
X_train, y_train, X_test, y_test = train_test_split(X, y, test_size=0.2, random_state=1)


In [101]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load the Iris dataset
dataset = pd.read_csv('Iris.csv')

# Separate features and target
X = dataset.drop(columns= 'Species')
y = dataset['Species']

print(X)
print(y)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virgin

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])